### ISSUE TITLE
Connect to local gitlab installation

### ISSUE THREAD

**Issue by jorgebnunes** [Its-treason/insomnia-plugin-git-integration#1]
Hi, 

First of all, thanks for your work!
Regarding this plugin, should be possible to connect to local gitlab instances.
Regards,
Jorge

**Comment by Its-treason** [comment]
Greetings @jorgebnunes, 

thank you for interest in this Plugin and taking your time to create an Issue.

Connecting to GitLab & GitHub using their API like Insomnia does (See: https://docs.insomnia.rest/insomnia/git-sync#set-up-a-remote-repository-with-gitlab) is planned for the future, when all base features are finished.

For now, the only connection method is Git with SSH. There are many articles that guide you through the setup process, e.g. the official GitLab article: https://docs.insomnia.rest/insomnia/git-sync#set-up-a-remote-repository-with-gitlab.

**Comment by jorgebnunes** [comment]
Oh, I see.
Thanks again!

Regards
