### ISSUE TITLE
Insomnium support

### ISSUE THREAD

**Issue by luisfavila** [Its-treason/insomnia-plugin-git-integration#10]
Hi! I've seen that this doesn't work on recent versions of insomnia, but we have insomnium now: https://github.com/ArchGPT/insomnium/

Would it be possible to support insomnium, given it's fully local?

**Comment by Its-treason** [comment]
Hey, this plugin should work with Insomnium. But I get an error during installation, which is weird. I look into fixing it, so it works with Insomnium.

Edit: Setting it up locally works, there might be something wrong with the version published on NPM.

**Comment by Its-treason** [comment]
Hey @luisfavila, I published version `0.6.5` that should work with Insomnium. Could you check if it is also working for you?

**Comment by luisfavila** [comment]
Will do tomorrow @Its-treason, thank you!

P.S. Local version does work indeed

**Comment by luisfavila** [comment]
Working great! Thank you 👋
