### ISSUE TITLE
Menu Items missing after plugin install

### ISSUE THREAD

**Issue by Quentinb** [Its-treason/insomnia-plugin-git-integration#2]
Thanks for building this! thought I'd give it a try. After install, the menu items are missing on the `create` menu
<img width="225" alt="image" src="https://user-images.githubusercontent.com/5852237/232251134-5016984a-590c-4af0-87c7-5cea5b5b0c93.png">
I'm on the Beta version of Insomnia
<img width="275" alt="image" src="https://user-images.githubusercontent.com/5852237/232251160-b6c0390c-c936-44ff-82f2-2a09a068fd30.png">

**Comment by Its-treason** [comment]
This is pretty sure, due to the Beta-Version of Insomnia.

Although it is strange that only the buttons are missing. Do you see any errors in the browser console?

I'm also going to try the beta version and see if there are any issues.

Thank you for reporting!

**Comment by Its-treason** [comment]
I just installed the Beta of Insomnia and everything looks fine. I think this might be a problem with macOS.

Sadly, I don't have a Mac, so I would greatly appreciate if you can send the error you are getting.

**Comment by Quentinb** [comment]
Had a look but don't see any errors, just a warning about react dev tools. I'll try it on a clean VM to see if it loads there. Might be something specific to my machine
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/5852237/232278147-ebf9ad2b-e647-4a3a-af5e-be49b5d1b285.png">

**Comment by Its-treason** [comment]
Are you using the default `Insomnia` Project? The Plugin will not work with the default project because the project ID is hard-coded into Insomnia, which makes it difficult to sync.

If that was the case, you can create a new project and move all your existing workspaces into the project using Insomnia's duplicate function.

This is definitely not very user-friendly and confusing. I'm going to extend the plugins documentation and add an info text for the default project.

**Comment by Quentinb** [comment]
Sorry I missed this message. I've retried it now and Yes, default project is the issue! Thanks for that info.
<img width="191" alt="image" src="https://user-images.githubusercontent.com/5852237/235287779-b18e5447-367c-438e-8ae3-ab05e786ffe0.png">
Switching to a new project:
<img width="184" alt="image" src="https://user-images.githubusercontent.com/5852237/235287798-94e04fe2-7fd7-4292-ae09-4c16e8a99ea5.png">
