### ISSUE TITLE
'Commit changes' has no reaction when clicked

### ISSUE THREAD

**Issue by ryan961** [Its-treason/insomnia-plugin-git-integration#3]
I have completed the 'Setup with existing project' step, but when I import the interface file(such as: https://github.com/postmanlabs/newman/blob/2a57036bc96c6e06289238cb4ef3fe70c1f9f338/test/integration/whatwg-url.postman_collection.json), I execute 'Commit changes' and nothing happens.
![image](https://user-images.githubusercontent.com/32825698/234520457-21502947-0a59-4196-91f8-19c793b37e83.png)

**Comment by Its-treason** [comment]
There might be a Problem with exporting your project. Do you see any Errors in the Console when clicking "Commit changes"?

**Comment by ryan961** [comment]
Thank you for your reply. Nothing happens clicking "Commit changes", I downloaded the installation package from the official website, I wonder if you can reproduce it.

Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Darwin x64 21.3.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by Its-treason** [comment]
Could you provide me with logs from Insomnia's Browser-Console / Dev-Tools? You can open them using Ctrl + Alt + I.

**Comment by ryan961** [comment]
I have followed your instructions and opened the console, and there is an error message.
![image](https://user-images.githubusercontent.com/32825698/234744004-f0b71d92-b720-4ab6-8926-72a8454eb97b.png)

**Comment by Its-treason** [comment]
Sorry for the wait, I had some work / personal stuff to do, but I found the problem and hopefully fixed your issue.

There seems to be a Problem with the Metadata for a folder not existing. This also happens with Metadata for other Items like Requests. I'm not entirely sure why this happens, Insomnia sometimes just doesn't create the Metadata.

The folder metadata only contains the information whether the folder is collapsed, so as a workaround, the plugin will now create the metadata if it couldn't be found. Be sure to install version 0.5.4 of the plugin.

**Comment by ryan961** [comment]
That's great, thanks for fixing it.
