### ISSUE TITLE
No new 'Create' UI buttons

### ISSUE THREAD

**Issue by leikoilja** [Its-treason/insomnia-plugin-git-integration#4]
**Describe the bug**
Just installed the plugin on the latest Version: Insomnia 2023.2.2 and no UI buttons are appearing in 'Create' dropdown.

<img width="337" alt="image" src="https://github.com/Its-treason/insomnia-plugin-git-integration/assets/10655107/8c4c1b91-820b-4af8-a5d1-f8bce963a12f">

**Comment by Its-treason** [comment]
Hello @leikoilja,

there's indeed a new button, it is the “Configure project” at the bottom of the dropdown.

You have to first configure a project path, then the buttons for exporting and importing will appear. After adding a git repository in the project directory (or its parent directory) the git push, pull & commit buttons will be shown.

If this doesn't work, or you have other question, feel free to comment here again!

**Comment by leikoilja** [comment]
great, thank you, i found it now :)
