### ISSUE TITLE
Error installing Plugin through Insomina UI

### ISSUE THREAD

**Issue by agodlydeciple** [Its-treason/insomnia-plugin-git-integration#5]
On Insomnia v2023.2.2 when trying to install the plugin through the plugin manager I receive the following error:
![image](https://github.com/Its-treason/insomnia-plugin-git-integration/assets/683837/6268f6c1-4ea2-4ef5-abc9-fcfe510faacc)

I have tried to install the plugin manually, but seem to be running into different issues there. Any and all help would great!

Thank you!

**Comment by agodlydeciple** [comment]
it appears that there is a license value in the package.json and this may be an insomnia issue itself.

**Comment by Its-treason** [comment]
Hello, thank you for opening this issue,

i tried installing the plugin on the latest version `2023.3.0` and it worked just fine. The new version might have fixed your installation issue or there might be an other problem with Insomnia or your system, i'm not sure.

If you get any new information or find a problem with the plugin: i'm glad to help

**Comment by jonathan-vandal** [comment]
I had the same error while installing Insomnia via the Ubuntu Software package. I installed Insomnia via the .deb provided on the site https://insomnia.rest/download and I no longer had the problem.

**Comment by Its-treason** [comment]
There is a problem with installing plugins, when Insomnia is installed as a Snap package. See: https://github.com/Kong/insomnia/issues/4316

As a workaround:
- Open Insomnia plugin folder (`Reveal Plugins Folder` in Plugin settings tab)
- Clone the project in the folder
- go into the project folder to execute `yarn install` and `yarn build`

When updating the plugin, you have to manually git pull and then execute `yarn install` and `yarn build` again.
