### ISSUE TITLE
Support for gitignore

### ISSUE THREAD

**Issue by RalphHolland** [Its-treason/insomnia-plugin-git-integration#9]
Hi

would it be possible to add a gitignore functionality , in my case for environment, as I don't want all my password and other secure data shared

also maybe a way in environments to set fields as secure and replace the value with "****" before the commit

Thanks

**Comment by Its-treason** [comment]
Hello @RalphHolland, if you do not want to export an environment and its variables, you can create a “Private environment” in Insomnia, these environments will not be exported.

**Comment by RalphHolland** [comment]
Thanks for the quick response, and that's perfect.

I had thought that it was a private one but when I checked it wasn't
